server:
  port: 80

spring:
  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379

security:
  static-path:
    - "/staticPath1"
    - "/staticPath2"
  permit-all-path:
    - "/login"
    - "/logout"
    - "/signUp"

#logging:
#  level:
#    org.springframework.security: DEBUG

jwt:
  secretKey: qweasdzxcrtyfghvbn1230984567)(*&^%$#@!
#  access-token-expire-time: 1800000      # 30분
  access-token-expire-time: 30000
  refresh-token-expire-time: 604800000   # 7일